### ISSUE TITLE
Agent hangs when timeline.json is modified

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#116]
When I make a change in the timeline, the agent seems to hang and can't kill the processes properly(Outlook, Word, PowerPoint still running). I also see a folder C:\Projects\Ghosts which I don't have it. 

```
2022/08/19 08:46:41.911|Ghosts.Client.TimelineManager.Orchestrator.OnChanged|FileWatcher event raised: C:\exercise\ghosts\config\timeline.json timeline.json Changed
2022/08/19 08:46:41.916|Ghosts.Client.TimelineManager.Orchestrator.OnChanged|FileWatcher Processing: C:\exercise\ghosts\config\timeline.json Changed
2022/08/19 08:46:41.916|Ghosts.Client.TimelineManager.Orchestrator.OnChanged|Reloading Ghosts.Client.TimelineManager.Orchestrator
2022/08/19 08:46:41.916|Ghosts.Client.TimelineManager.Orchestrator.OnChanged|terminate existing tasks and rerun orchestrator
2022/08/19 08:46:41.929|Ghosts.Client.Handlers.Cmd..ctor|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:41.947|Ghosts.Client.Handlers.WordHandler.ExecuteEvents|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:46.949|Ghosts.Client.Handlers.WordHandler.ExecuteEvents|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:46.994|Ghosts.Client.Infrastructure.ProcessManager.KillProcessAndChildrenByName|Closing WINWORD threw exception - System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Ghosts.Domain.Code.Helpers.ProcessExtensions.SafeKill(Process process)
   at Ghosts.Client.Infrastructure.ProcessManager.KillProcessAndChildrenByName(String procName) in C:\Projects\ghosts\src\Ghosts.Client\Infrastructure\ProcessManager.cs:line 83
2022/08/19 08:46:46.994|Ghosts.Client.Handlers.WordHandler.ExecuteEvents|Word closing...
2022/08/19 08:46:46.994|Ghosts.Client.Infrastructure.ProcessManager.GetPids|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:46.994|Ghosts.Client.Handlers.WordHandler..ctor|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:47.026|Ghosts.Client.Infrastructure.ProcessManager.KillProcessAndChildrenByName|Closing WINWORD threw exception - System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Ghosts.Domain.Code.Helpers.ProcessExtensions.SafeKill(Process process)
   at Ghosts.Client.Infrastructure.ProcessManager.KillProcessAndChildrenByName(String procName) in C:\Projects\ghosts\src\Ghosts.Client\Infrastructure\ProcessManager.cs:line 83
2022/08/19 08:46:47.039|Ghosts.Client.Handlers.ExcelHandler.ExecuteEvents|Excel handler exception: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at Ghosts.Client.Handlers.ExcelHandler.ExecuteEvents(Timeline timeline, TimelineHandler handler) in C:\Projects\ghosts\src\Ghosts.Client\Handlers\Excel.cs:line 66
2022/08/19 08:46:51.351|Ghosts.Client.Comms.Updates.PostClientResults|C:\exercise\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/08/19 08:46:52.040|Ghosts.Client.Handlers.ExcelHandler.ExecuteEvents|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:52.067|Ghosts.Client.Handlers.ExcelHandler.ExecuteEvents|Excel closing...
2022/08/19 08:46:52.069|Ghosts.Client.Handlers.ExcelHandler..ctor|Excel launch handler exception: System.Threading.ThreadAbortException: Thread was being aborted.
   at Ghosts.Client.Handlers.ExcelHandler.ExecuteEvents(Timeline timeline, TimelineHandler handler) in C:\Projects\ghosts\src\Ghosts.Client\Handlers\Excel.cs:line 66
   at Ghosts.Client.Handlers.ExcelHandler..ctor(Timeline timeline, TimelineHandler handler) in C:\Projects\ghosts\src\Ghosts.Client\Handlers\Excel.cs:line 39
2022/08/19 08:46:52.103|Ghosts.Client.Handlers.PowerPointHandler.ExecuteEvents|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:57.105|Ghosts.Client.Handlers.PowerPointHandler.ExecuteEvents|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:57.133|Ghosts.Client.Infrastructure.ProcessManager.KillProcessAndChildrenByName|Closing POWERPNT threw exception - System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Ghosts.Domain.Code.Helpers.ProcessExtensions.SafeKill(Process process)
   at Ghosts.Client.Infrastructure.ProcessManager.KillProcessAndChildrenByName(String procName) in C:\Projects\ghosts\src\Ghosts.Client\Infrastructure\ProcessManager.cs:line 83
2022/08/19 08:46:57.133|Ghosts.Client.Handlers.PowerPointHandler.ExecuteEvents|PowerPoint closing...
2022/08/19 08:46:57.133|Ghosts.Client.Handlers.PowerPointHandler..ctor|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:57.159|Ghosts.Client.Infrastructure.ProcessManager.KillProcessAndChildrenByName|Closing POWERPNT threw exception - System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Ghosts.Domain.Code.Helpers.ProcessExtensions.SafeKill(Process process)
   at Ghosts.Client.Infrastructure.ProcessManager.KillProcessAndChildrenByName(String procName) in C:\Projects\ghosts\src\Ghosts.Client\Infrastructure\ProcessManager.cs:line 83
2022/08/19 08:46:57.159|Ghosts.Client.Handlers.Outlook.ExecuteEvents|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:57.159|Ghosts.Client.Handlers.Outlook..ctor|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:57.172|Ghosts.Client.Handlers.BaseBrowserHandler.ExecuteEvents|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:57.505|Ghosts.Client.Handlers.BrowserChrome..ctor|System.Threading.ThreadAbortException: Thread was being aborted.
2022/08/19 08:46:57.567|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Got ghosts pid: 5580
2022/08/19 08:46:57.570|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing chromedriver
2022/08/19 08:46:57.570|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing WINWORD
2022/08/19 08:46:57.570|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing POWERPNT
2022/08/19 08:46:57.570|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing EXCEL
2022/08/19 08:46:57.570|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing chrome
2022/08/19 08:46:57.570|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing OUTLOOK
2022/08/19 08:46:57.570|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing cmd
2022/08/19 08:46:57.592|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing powershell
2022/08/19 08:46:57.592|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing geckodriver
2022/08/19 08:46:57.592|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing firefox
2022/08/19 08:46:57.592|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing werfault
2022/08/19 08:46:57.592|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing werfaultsecure
2022/08/19 08:46:57.602|Ghosts.Client.Infrastructure.StartupTasks.CleanupProcesses|Killing ghosts
```

**Comment by sei-dupdyke** [comment]
`C:\Projects\ghosts`... is a reference to the source, you'd not have that on a client machine.

These errors really shouldn't be a show-stopper, but I fixed them in 6.1.7 which is out there now.
