### ISSUE TITLE
Posting outlookv2 handlertype to /timelines gave internal server error

### ISSUE THREAD

**Issue by sirbowen78** [cmu-sei/GHOSTS#203]
I was posting to /timelines with the following json data, so that ghosts agent can save the attachment of an email:
```{
  "machineId": "84b063ce-4a87-4bfb-a1ec-c9b981d3bff5",
  "type": "Timeline",
  "update": {
    "TimeLineHandlers": [
      {
      "HandlerType": "Outlookv2",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24.00:00:00",
      "Loop": true,
        "HandlerArgs": {
        "delay-jitter": 50,
        "delete-probability": 0,
        "create-probability": 0,
        "read-probability": 100,
        "reply-probability": 0,
          "click-probability": 0,
        "attachment-probability": 0,
        "save-attachment-probability": 100,
          "download-probability": 100,
        "min-attachments": 5,
        "max-attachments": 5,
        "input-directory": "C:\\ghosts_data\\uploads",
        "output-directory": "C:\\ghosts_data\\downloads"
      },
      "TimeLineEvents": [
        {
          "Command": "read",
          "CommandArgs": [],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
    ]
  }
    ]
  }
}
```

The API server returns a 500 Internal Server Error, the above json was based on the sample json, I am not sure which part has caused the internal server error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ghosts.Api.Services.TimelineService.UpdateAsync(MachineUpdateViewModel machineUpdateViewModel, CancellationToken ct) in /app/Ghosts.Api/Services/TimelineService.cs:line 39
   at ghosts.api.Controllers.TimelinesController.Timeline(MachineUpdateViewModel machineUpdate, CancellationToken ct) in /app/Ghosts.Api/Controllers/TimelinesController.cs:line 70
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by sei-dupdyke** [comment]
I tested your json POST here and it works for me. 

Did you newly install v7 recently, or did you upgrade an existing installation?

**Comment by sirbowen78** [comment]
Hi,
I am using the Ghost API version 7, no upgrade, I am following your quick installation guide by using the docker compose..Hmm this is weird, perhaps I will reboot the API server...

**Comment by sirbowen78** [comment]
Hi, thank you for your response, however I restarted the ghosts-api, I still have the internal server error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ghosts.Api.Services.TimelineService.UpdateAsync(MachineUpdateViewModel machineUpdateViewModel, CancellationToken ct) in /app/Ghosts.Api/Services/TimelineService.cs:line 35
   at ghosts.api.Controllers.TimelinesController.Timeline(MachineUpdateViewModel machineUpdate, CancellationToken ct) in /app/Ghosts.Api/Controllers/TimelinesController.cs:line 68
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
It seems there is a problem in updating timeline, did you use the exact json data which I posted here? if not can you share the one that worked? 
I tried removing the "update" key, although ghosts-api accepted this, the timeline became "null" in the ghosts agent, so no matter what it seems I must add "update" key when posting to /timelines...

**Comment by sei-dupdyke** [comment]
Hmm, I posted what you have [here](https://github.com/cmu-sei/GHOSTS/issues/203#issue-1648584993) (I just had to add an opening "{" character):

```
{
  "machineId": "84b063ce-4a87-4bfb-a1ec-c9b981d3bff5",
  "type": "Timeline",
  "update": {
    "TimeLineHandlers": [
      {
      "HandlerType": "Outlookv2",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24.00:00:00",
      "Loop": true,
        "HandlerArgs": {
        "delay-jitter": 50,
        "delete-probability": 0,
        "create-probability": 0,
        "read-probability": 100,
        "reply-probability": 0,
          "click-probability": 0,
        "attachment-probability": 0,
        "save-attachment-probability": 100,
          "download-probability": 100,
        "min-attachments": 5,
        "max-attachments": 5,
        "input-directory": "C:\\ghosts_data\\uploads",
        "output-directory": "C:\\ghosts_data\\downloads"
      },
      "TimeLineEvents": [
        {
          "Command": "read",
          "CommandArgs": [],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
    ]
  }
    ]
  }
}
```

I get back 204 No Content, which means the request was accepted successfully:

![image](https://user-images.githubusercontent.com/43444464/229514442-c1e4dbfe-d024-4e7b-ba5e-3a195989eacb.png)

**Comment by sirbowen78** [comment]
![image](https://user-images.githubusercontent.com/53977230/229669024-3951196f-cc8a-409c-b5ef-d3bb0f3a05a6.png)
I believe there is nothing wrong with the docker images right?

![image](https://user-images.githubusercontent.com/53977230/229669235-9605208e-2219-4155-9d14-d53abc79d8f0.png)
I compared your json with mine...  both are the same...

I think the last thing I need to do is to do a docker-compose down and redo docker-compose up -d and see if the problem still persists or not, only this outlookv2 has internal server error, I have no issue with outlook, browserchrome, browserfirefox, command handlertypes.

Is there any debug logs I can turn on on the ghosts-api?

**Comment by sei-dupdyke** [comment]
Hmm, when you mentioned the containers, I was thinking that maybe something isn't in the latest build on docker hub that I have here, so I pushed latest—or you can specify the version explicitly via:

`docker pull dustinupdyke/ghosts:7.0.18`

Please update your docker-compose.yml file to use this image, I already updated it [in the repo](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Api/docker-compose.yml#L36).

Sorry for the inconvenience.

**Comment by sirbowen78** [comment]
Hi,

Thank you. the ghosts-api to 7.0.18 solves the problem. I have updated and sent in the previous json i presented here,the ghosts-api accepted the json. Thank you again.
