### ISSUE TITLE
Errors with Sample Timelines

### ISSUE THREAD

**Issue by GeorgiNikolovRMA** [cmu-sei/GHOSTS#33]
Hello,

currently I am testing the project with the sample timelines provided. I ran into multiple errors along the way:

- In "trackable timeline.json"

```
2020/05/31 16:04:43.589|Ghosts.Client.Handlers.BaseBrowserHandler.ExecuteEvents|OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@class, 'dl')]"}
  (Session info: chrome=81.0.4044.129)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Ghosts.Client.Handlers.BaseBrowserHandler.ExecuteEvents(TimelineHandler handler) in Z:\Projects\ghosts\Ghosts.Client\Handlers\BaseBrowserHandler.cs:line 136
```

(Also side question, do we need to ourselves give the guid of the trackable element from the postgres db in the timeline under: "TrackableId": "<guid id from trackables table/>",)

- In "BrowserFirefox.json"

```
2020/05/31 16:36:29.037|Ghosts.Client.Handlers.BaseBrowserHandler.ExecuteEvents|System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Ghosts.Domain.Code.StringExtensions.ToFormValueString[TKey,TValue](IDictionary`2 dictionary)
   at Ghosts.Client.Handlers.BaseBrowserHandler.MakeRequest(RequestConfiguration config) in Z:\Projects\ghosts\Ghosts.Client\Handlers\BaseBrowserHandler.cs:line 199
   at Ghosts.Client.Handlers.BaseBrowserHandler.ExecuteEvents(TimelineHandler handler) in Z:\Projects\ghosts\Ghosts.Client\Handlers\BaseBrowserHandler.cs:line 69
```

Running the GHOSTS project on Windows 10 VirtualBox VM
***Chrome Version***: Version 81.0.4044.129 (Official Build) (64-bit)
***Firefox Version***: 76.0.1 (64-bit)

Any suggestions?

**Comment by sei-dupdyke** [comment]
Hi!

The first error is an xpath error, so I think the following is happening:

```
               {
                    "Command": "browse",
                    "CommandArgs": [ "https://dl.dafont.com/dl/?f=italian_breakfast" ],
                    "DelayAfter": 0,
                    "DelayBefore": 0
                },
                {
                    "Command": "download",
                    "CommandArgs": [ "//a[contains(@class, 'dl')]" ],
                    "TrackableId": "<guid id from trackables table/>",
                    "DelayAfter": 0,
                    "DelayBefore": 0
                }
```

the first command is to browse to a page on dafont.com and the second is to click an <a href tag with a class of "dl". This page probably has changed and the link no longer exists. In this example, we replicate the internet and this site to host drive-by malware for download. You'd have to either replicate this domain in your own range, or change the url and href to actual existing values.

The trackable ID can be any guid you like. It simply gives you a datapoint to query on in the database table of timelinehistory records. So that if you're waiting for an agent to perform some series of actions, you can track those actions by the IDs you assign them.

For the BrowserFirefox.json file, try changing the urls to actual sites. I'm getting errors because there is no dns for the ones in the sample, sorry, I should update those!
