### ISSUE TITLE
64 bit Office Version Requires 64 bit version of GHOSTS

### ISSUE THREAD

**Issue by taschultz** [cmu-sei/GHOSTS#49]
I ran an instance of GHOSTS on a 64 Bit Windows 10 VM with Office 2016 x64 installed. Redemption was present and I even updated to the current release (20 Nov 2020); but still received the following error message: 

> 2020/11/25 18:09:52.824|Ghosts.Client.Handlers.Outlook..ctor|RDO load error: System.Runtime.InteropServices.COMException (0x800401FA): Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP))
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.IClassFactory.CreateInstance(Object pUnkOuter, Guid& refiid, Object& ppunk)
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.NewRedemptionObject(Guid guid) in Z:\Projects\ghosts\src\Ghosts.Client\Infrastructure\Email\RedemptionLoader.cs:line 256
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.new_RDOSession() in Z:\Projects\ghosts\src\Ghosts.Client\Infrastructure\Email\RedemptionLoader.cs:line 27
   at Ghosts.Client.Handlers.Outlook..ctor(TimelineHandler handler) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 44
2020/11/25 18:09:53.595|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381

The current deafult project build settings had a "Platform Target" of "Any" with "Prefer 32-bit" checked. 

Fix action per http://www.dimastr.com/redemption/faq.htm#ErrorCreatingRedemptionObject is to compile and a x64 version of GHOSTS using Visual Studio for instances where 64 bit Outlook is being used. I was able to confirm this change corrected the Outlook issue.

**Comment by sei-dupdyke** [comment]
Hi, sorry I was out for a few days on PTO... thanks for looking into this. I will add to wiki.

Maybe a larger problem here is that I've coded to specific CLSIDs for the version of Office that we use. Should probably look at dynamic ways of determining the installed versions.

**Comment by sei-dupdyke** [comment]
Thinking that perhaps v5 will have both a 32 and 64-bit build and users can choose whichever suits them best.

**Comment by sei-dupdyke** [comment]
[I released an x64 version of the client today](https://cmu.box.com/s/3vpo16sbm8dg52p4tn129h0l6rjj9iuz), v4, no other new features.

Note that Office 365 x64 falls back to 32-bit under the hood, so the latter client seems to work fine for those installations.

Any issues with it, please let me know.
