### ISSUE TITLE
Chrome Binary Not Found Error

### ISSUE THREAD

**Issue by taschultz** [cmu-sei/GHOSTS#50]
The default code base lacks the path to the Chrome executable. Original error message:

> 2020/11/25 18:09:48.256|Ghosts.Client.Handlers.BrowserChrome..ctor|OpenQA.Selenium.WebDriverException: unknown error: cannot find Chrome binary
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at Ghosts.Client.Handlers.BrowserChrome..ctor(TimelineHandler handler) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\BrowserChrome.cs:line 63

Manually adding the below line to BrowserChrome.cs appears to resolve the issue

`options.BinaryLocation = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";`

**Comment by sei-dupdyke** [comment]
Thanks for posting this. I need to make a change to allow for incognito mode as well, and I'll add this change in as well.

**Comment by sei-dupdyke** [comment]
This seems related to a mismatch with [ChromeDriver versioning](https://chromedriver.chromium.org/downloads). I don't recall there being such a tight binding from one to the other in terms of versioning with GeckoDriver, but I'll have to check.

**Comment by sei-dupdyke** [comment]
Still, I'm adding a arg for the timeline to specify location:

```json
{
            "HandlerType": "BrowserChrome",
            "HandlerArgs": {
                "executable-location": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
```

**Comment by sei-dupdyke** [comment]
I'm also adding a default check to see if the executable is in `Program Files` or `Program Files (x86)`

**Comment by sei-dupdyke** [comment]
This is working with check-in e939fc..., will be available in next binary release.

**Comment by lixiaomeng** [comment]
It does not work with the key "executable-location"

**Comment by sei-dupdyke** [comment]
Quick check: Does your chromedriver version match your chrome version?
