### ISSUE TITLE
multiple errors in Ghost-Api when connecting the v4 client

### ISSUE THREAD

**Issue by nunoguerreiro** [cmu-sei/GHOSTS#61]
using the last docker-compose and v4 client - having multiple errors in the ghost-api container

![image](https://user-images.githubusercontent.com/1771943/111018369-ddf29c00-83d1-11eb-9bfa-b3310c22f199.png)

**Comment by sei-dupdyke** [comment]
Hi -

At first glance, this looks like a version mismatch between the client and API - Can you hit `/api/home` (something like http://localhost:5000/api/home) and see if it returns basic "online" info?

**Comment by fhbermudez** [comment]
I am getting similar messages:
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
ghosts-api    |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.

 fail: Microsoft.AspNetCore.Server.Kestrel[13]
ghosts-api    |       Connection id "0HM75GTI1LOF0", Request id "0HM75GTI1LOF0:00000006": An unhandled exception was thrown by the application.
ghosts-api    |       Ghosts.Api.Infrastructure.Exceptions+GhostsClientFormattingException: Web Headers are not configured correctly
ghosts-api    |          at Ghosts.Api.Controllers.ClientIdController.Index(CancellationToken ct) in /app/Ghosts.Api/Controllers/ClientIdController.cs:line 40
ghosts-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)



When opening "localhost:5000/api/home" It does display the correct number of clients.
The Grafana is displaying the number of agents and the agent's activities.
Also noticed that on the GHOSTS API interface with Swagger, the "Home" and "​/api​/machines​/list" are the only commands I have gotten to work or respond.

**Comment by sei-dupdyke** [comment]
Hmm, are you hitting /ClientId directly? The client specific endpoints need a specially constructed request that the client is programmed to do, but hitting it with the browser will cause this error:

> ghosts-api | Ghosts.Api.Infrastructure.Exceptions+GhostsClientFormattingException: Web Headers are not configured correctly

**Comment by sei-dupdyke** [comment]
Sorry, to be more clear, the client endpoints are:

ClientId
    - ​/api​/clientid
    - Clients use this endpoint to get their unique GHOSTS system ID

ClientResults
    - ​/api​/clientresults
    - Clients post a timeline or health payload to this endpoint

ClientSurvey
    - POST
    - ​/api​/clientsurvey​/secure
    - Clients post an encrypted survey results to this endpoint
    -    
    - POST
    - ​/api​/clientsurvey
    - Clients post survey results to this endpoint

ClientTimeline
    - POST
    - ​/api​/clienttimeline
    - Clients pot their timelines here, so that the C2 knows what a particular agent is doing

ClientUpdates
    - GET
    - ​/api​/clientupdates
    - Clients use this endpoint to check for updates for them to download

These are meant to be hit by the client. You should have no need to hit these in the browser or otherwise.

**Comment by nunoguerreiro** [comment]
> http://localhost:5000/api/home)

Hi @sei-dupdyke see below - I'm using the official githut docker-composer and client zip file distributed in the wiki.

![image](https://user-images.githubusercontent.com/1771943/111222981-f6430080-85f5-11eb-83f1-82844f27cf16.png)

![image](https://user-images.githubusercontent.com/1771943/111223136-2d191680-85f6-11eb-8999-2590684e9893.png)

![image](https://user-images.githubusercontent.com/1771943/111223169-399d6f00-85f6-11eb-8ffc-b9c965e78471.png)

I see, client is V4 and Server is V5.
The "question" is how to use Server v4. ? what is the docker image to use ?

**Comment by nunoguerreiro** [comment]
@sei-dupdyke  shall we use this docker image instead since the client is the v4 ?

docker pull dustinupdyke/ghosts:v4.0.0.0 ???

**Comment by sei-dupdyke** [comment]
5 should be good to go, I just tried it. It looks like /api/home is working. Which endpoint are you hitting that is causing your error above in the initial post?

**Comment by nunoguerreiro** [comment]
> 5 should be good to go, I just tried it. It looks like /api/home is working. Which endpoint are you hitting that is causing your error above in the initial post?

any. I tried with a simple timeline command task - issue is the same...

With V4 - not happens (e.g. no error) but no data in database timelines (and in grafana off course)

I really tried multiple options and no results and the errors above...

![image](https://user-images.githubusercontent.com/1771943/111228613-ec250000-85fd-11eb-8f71-52c4858b2920.png)

**Comment by nunoguerreiro** [comment]
forgot to mention, I'm using the same files coming in the client v4 with only changes in the endpoints (server IP and port).

**Comment by sei-dupdyke** [comment]
Okay, sorry, let me dig in here a bit. Standby.

**Comment by sei-dupdyke** [comment]
Okay, try this test please. I'm on v5, testing with the swagger interface (http://localhost:5000/index.html):

![Screen Shot 2021-03-15 at 7 12 55 PM](https://user-images.githubusercontent.com/43444464/111233067-adbe1f80-85c2-11eb-9dc4-d07291b4b43c.png)

Let's get all the machines: 
![Screen Shot 2021-03-15 at 7 13 19 PM](https://user-images.githubusercontent.com/43444464/111233091-b9a9e180-85c2-11eb-846c-4baf99b1af87.png)

Take a machine id and try to update its timeline:
![Screen Shot 2021-03-15 at 7 14 21 PM](https://user-images.githubusercontent.com/43444464/111233161-d8a87380-85c2-11eb-9d44-bf96f8148247.png)

LMK please.

**Comment by nunoguerreiro** [comment]
> Okay, try this test please. I'm on v5, testing with the swagger interface (http://localhost:5000/index.html):
> 
> ![Screen Shot 2021-03-15 at 7 12 55 PM](https://user-images.githubusercontent.com/43444464/111233067-adbe1f80-85c2-11eb-9dc4-d07291b4b43c.png)
> 
> Let's get all the machines:
> ![Screen Shot 2021-03-15 at 7 13 19 PM](https://user-images.githubusercontent.com/43444464/111233091-b9a9e180-85c2-11eb-846c-4baf99b1af87.png)
> 
> Take a machine id and try to update its timeline:
> ![Screen Shot 2021-03-15 at 7 14 21 PM](https://user-images.githubusercontent.com/43444464/111233161-d8a87380-85c2-11eb-9d44-bf96f8148247.png)
> 
> LMK please.

![image](https://user-images.githubusercontent.com/1771943/111395559-940dfc80-86d6-11eb-9d22-a96b849f4838.png)

![image](https://user-images.githubusercontent.com/1771943/111395509-72147a00-86d6-11eb-9973-da72f45f01a4.png)

![image](https://user-images.githubusercontent.com/1771943/111395840-3af29880-86d7-11eb-86bd-5f6c46341b4f.png)

**Comment by sei-dupdyke** [comment]
I've recreated the issue a few times, it looks like the API container is not waiting for the Postgres server to be accepting connections, and then I see this weird spate of errors like you are getting above, even though it looks like (?) the command did complete...

Can you try either 
1. Bringing up the Postgres container separately first, and then the ghosts API container once it is accepting connections?
2. Brining up the docker-compose as normal, but then restarting the ghosts API container once everything is up as to ensure the API can connect to Postgres at startup?

Sorry for the hassle. I thought we had fixed this issue of startup timing, perhaps it is back.

**Comment by nunoguerreiro** [comment]
> I've recreated the issue a few times, it looks like the API container is not waiting for the Postgres server to be accepting connections, and then I see this weird spate of errors like you are getting above, even though it looks like (?) the command did complete...
> 
> Can you try either
> 
> 1. Bringing up the Postgres container separately first, and then the ghosts API container once it is accepting connections?
Done. same issue.  Postgres was working and accepting connections - then started api and same error.

> 2. Brining up the docker-compose as normal, but then restarting the ghosts API container once everything is up as to ensure the API can connect to Postgres at startup?

Done. same issue.  started all, then stopped api only. Postgres was still working and accepting connections - then started api container and same error.

> 
> Sorry for the hassle. I thought we had fixed this issue of startup timing, perhaps it is back.

Did both options . Same issues....

**Comment by nunoguerreiro** [comment]
Other option to try this is in visual studio - tried to find a way now to run the api in dev mode, and connect the client... exactly same issue during dev.

**Comment by sei-dupdyke** [comment]
Oof, [I found a bug here and just posted a fix up](https://github.com/cmu-sei/GHOSTS/commit/ad1a381992000b84da5a6531963fec95867f2c5f#diff-47cca518bae69adb2deee9a8b331e194ff45587622e4b89f4e07cbbd4eb2b8d1L40) — the clientid on first run is null, and so that line would have always thrown an exception. My test here had a clientid and so (1) I didn't really recreate your situation (2) I changed my bad test to not have a clientid either.

I updated the docker images on hub.docker.com, if you force a new pull, you should get the new one, but if you want to be sure, update your docker-compose file line 35 to:

`image: dustinupdyke/ghosts:5.1`

Sorry for the confusion and bug.



 and just posted a fix up. Can you

**Comment by nunoguerreiro** [comment]
Hi @sei-dupdyke exactly .... i noted also that - the clientID (in the client) is null ... and could also replicate that.

Now I have a correct clientID (id.json in the client) and server no errors.
![image](https://user-images.githubusercontent.com/1771943/111716024-97d48700-886e-11eb-8a8a-e4b4d796b1be.png)

Nevertheless, the activities and health is not being updated in the database (postgres), and off course grafana does not show nothing.

![image](https://user-images.githubusercontent.com/1771943/111716090-c05c8100-886e-11eb-96d8-f63a7f0be3f5.png)

also confirmed via the API swagger.
![image](https://user-images.githubusercontent.com/1771943/111716151-dcf8b900-886e-11eb-9110-b91e21b6e897.png)

do you need all my client config files? I'm using the ones inside the ghosts client 4.0.
and I'm pretty sure all is right. 

to replicate I deleted all the volumes and restarted the docker-compose multiple times. there is really somewhere an issue... digging now.

**Comment by sei-dupdyke** [comment]
Check the client files in `/logs`:

1. Sometimes they fill to an unmanageable size, and the client then has trouble catching up and clearing them out. Delete them and they'll automatically be recreated.
2. Are there errors in the `/logs/app.log`? If they are connection errors to the now working server, we can look at the configuration for that, post the error here, please.

**Comment by nunoguerreiro** [comment]
Hi @sei-dupdyke  how to active the debug logging ?
I saw that ghosts.exe -d should activate the debug in the client but does not show anything nor in the logs nor in the console.

**Comment by sei-dupdyke** [comment]
That just spits out a couple of values for file locations and configuration. Overall, logging is controlled by the [nlog.config file here](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/nlog.config). If you want more detailed logging, you'd want to change line 9 minlevel value to "Trace", that will spit everything that is logged out to the file.

**Comment by nunoguerreiro** [comment]
@fhbermudez  @sei-dupdyke  exactly the same issue in my implementation.
server - 5.1, client 4.0 and nothing is displayed in grafana timeline or activities

![image](https://user-images.githubusercontent.com/1771943/113104347-78940d00-9211-11eb-889a-1ce926fb70a6.png)

Tried also a "fresh" installation using the client and server original packages and the same results. The polling is although showing some results but that's it.

**Comment by sei-dupdyke** [comment]
Hmm, I just tried:

1. `docker-compose up -d`
2. login to grafana, create datasource, import the dashboard
3. I have a tool in this repository for load testing, I pointed it at localhost:5000 and let it run a bit.
4. I had to "zoom out" on the time period that grafana is showing: 

![Screen Shot 2021-03-31 at 10 13 58 AM](https://user-images.githubusercontent.com/43444464/113158484-d3c20180-9209-11eb-91bd-cf5d38df6f11.png)

Of course, I can zoom back in now, I just wanted to make sure things were being logged correctly.

Can you confirm that zooming out you see any information?

If you want to try the load testing tool, I can put a compiled version on box for you to try as well.

**Comment by nunoguerreiro** [comment]
Hi @sei-dupdyke  yes . I did all that. zoom to current time, last hour and so on. I will reinstall all (deleting all containers and restart again). Not really sure what is happening. By the way if we have firewalls in the middle which ports I need to consider. At this moment no firewall rules are applied.

**Comment by sei-dupdyke** [comment]
Oh no! Hmm, let's look at some other things, please try this:
 
* Go to a client that you have set up, stop it if it is running (there should be a [kill-ghosts.bat](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/kill-ghosts.bat) script in the directory that you can use
* Delete the logs folder
* Run ghosts again and wait a few minutes 

What does the application.log say?
Did the clientresults.log file grow and then reset to zero bytes? (this would indicate a successful payload delivery up to the API) 

If this is all good to go, let's look at the postgres db on your API install:

* `docker exec -it ghosts-postgres sh` (you should get a command line on the postgres container)
* `psql -U ghosts` (gets you into postgres query on GHOSTS db)
* (might need `/c ghosts` to get to that db, but I don't think so...)
* `select * from history_timeline order by id desc limit 100;`

(you can change the limit if that is too many records)

What does the createdutc field look like? Here is mine locally:

![Screen Shot 2021-04-02 at 4 59 42 PM](https://user-images.githubusercontent.com/43444464/113453834-dfadef00-93d4-11eb-9680-c19b53ecc2bb.png)

**Comment by sei-dupdyke** [comment]
On your client machine, when you please check: 

1. the instance/id.json file - does it contain a uuid or is it blank?
2. the logs/app.log - does it contain any indication if the client updates are failing to be posted up to the server?

Thanks!

**Comment by MulvadT** [comment]
Hey 
1. 
The instance file have the following uuid: 
`673cfcee-fc00-4f0b-93f7-32a03c079570`

2. the app log is saying this: 

```
2021/08/30 14:26:22.813|Ghosts.Client.Infrastructure.Email.EmailContentManager.Check|Email content loaded successfully with 7891 records found
2021/08/30 14:26:35.770|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:26:36.768|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:26:37.770|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:26:39.774|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:26:41.784|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:26:44.864|Ghosts.Client.Comms.Updates.PostSurvey|System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at Ghosts.Client.Comms.Updates.PostSurvey() in Z:\Projects\ghosts\src\Ghosts.Client\Comms\Updates.cs:line 346
2021/08/30 14:29:29.940|Ghosts.Client.Infrastructure.Email.EmailContentManager.Check|Email content loaded successfully with 7891 records found
2021/08/30 14:29:42.281|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:29:43.282|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:29:44.287|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:29:46.312|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:29:48.304|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:29:49.365|Ghosts.Client.Comms.Updates.PostSurvey|System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at Ghosts.Client.Comms.Updates.PostSurvey() in Z:\Projects\ghosts\src\Ghosts.Client\Comms\Updates.cs:line 346
2021/08/30 14:34:57.847|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:34:58.857|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:34:59.851|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:35:01.859|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:35:03.868|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:35:04.874|Ghosts.Client.Comms.Updates.PostSurvey|System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at Ghosts.Client.Comms.Updates.PostSurvey() in Z:\Projects\ghosts\src\Ghosts.Client\Comms\Updates.cs:line 346
2021/08/30 14:40:13.261|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:40:14.288|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:40:15.263|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:40:17.267|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:40:19.278|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:40:20.287|Ghosts.Client.Comms.Updates.PostSurvey|System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at Ghosts.Client.Comms.Updates.PostSurvey() in Z:\Projects\ghosts\src\Ghosts.Client\Comms\Updates.cs:line 346
2021/08/30 14:45:28.463|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:45:29.462|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:45:30.463|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:45:32.469|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:45:34.483|Ghosts.Client.Survey.PowerShellManager.Error_DataAdded|System.Management.Automation.PSDataCollection`1[System.Management.Automation.ErrorRecord]
2021/08/30 14:45:35.489|Ghosts.Client.Comms.Updates.PostSurvey|System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at Ghosts.Client.Comms.Updates.PostSurvey() in Z:\Projects\ghosts\src\Ghosts.Client\Comms\Updates.cs:line 346
```

**Comment by sei-dupdyke** [comment]
Oh no, server API is throwing some sort of error, can you please do a `docker logs ghosts-api` to see what that might be please?

**Comment by MulvadT** [comment]
Hey 
Can see it is the same error as other has posted in this thread already. But mine looks like this: 
![DockerGhostLog](https://user-images.githubusercontent.com/59530411/131479328-f6e0f87b-79d5-45a8-9d72-381202910454.png)

My server api home returns this, just made a cleen install on a ubuntu server 20.04lts.  
![ServerAPIVersion](https://user-images.githubusercontent.com/59530411/131479766-0fa584fb-e1ff-4b0c-8f3a-42f6e17d3506.png)

And are using this windows client to test: 
![ClientStart](https://user-images.githubusercontent.com/59530411/131479810-78892d81-296a-4db3-836c-02092fa815e1.png)

**Comment by sei-dupdyke** [comment]
Sorry for the delay in responding. I just can't seem to recreate this issue (on API 5.0 and client 4.0). Still looking...

**Comment by sei-dupdyke** [comment]
In this image:

![](https://user-images.githubusercontent.com/59530411/131479328-f6e0f87b-79d5-45a8-9d72-381202910454.png)

This error is related the survey endpoint, and shouldn't have anything to do with client activity like browsing or executing powershell. Not good, I know but seems separate from no activity showing up for a given client. Still digging.
