### ISSUE TITLE
Outlook 2016

### ISSUE THREAD

**Issue by fhbermudez** [cmu-sei/GHOSTS#70]
I get the following error log in the "app" log when using Outlook 2016:
--------------BEGIN OF LOG ----------------------------------------------------------------------
2021/06/09 11:36:14.362|Ghosts.Client.Infrastructure.Email.EmailContentManager.Check|Email content loaded successfully with 7891 records found
2021/06/09 11:36:16.926|Ghosts.Client.Handlers.Outlook..ctor|RDO load error: System.Runtime.InteropServices.COMException (0x800401FA): Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP))
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.IClassFactory.CreateInstance(Object pUnkOuter, Guid& refiid, Object& ppunk)
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.NewRedemptionObject(Guid guid) in Z:\Projects\ghosts\src\Ghosts.Client\Infrastructure\Email\RedemptionLoader.cs:line 256
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.new_RDOSession() in Z:\Projects\ghosts\src\Ghosts.Client\Infrastructure\Email\RedemptionLoader.cs:line 27
   at Ghosts.Client.Handlers.Outlook..ctor(TimelineHandler handler) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 44
2021/06/09 11:36:16.926|Ghosts.Client.Handlers.Outlook..ctor|RDO load error: System.Runtime.InteropServices.COMException (0x800401FA): Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP))
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.IClassFactory.CreateInstance(Object pUnkOuter, Guid& refiid, Object& ppunk)
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.NewRedemptionObject(Guid guid) in Z:\Projects\ghosts\src\Ghosts.Client\Infrastructure\Email\RedemptionLoader.cs:line 256
   at Ghosts.Client.Infrastructure.Email.RedemptionLoader.new_RDOSession() in Z:\Projects\ghosts\src\Ghosts.Client\Infrastructure\Email\RedemptionLoader.cs:line 27
   at Ghosts.Client.Handlers.Outlook..ctor(TimelineHandler handler) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 44
2021/06/09 11:36:23.784|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381
2021/06/09 11:36:23.758|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381
2021/06/09 11:36:42.872|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381
2021/06/09 11:36:42.872|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381
2021/06/09 11:36:45.345|Ghosts.Client.Comms.Updates.GetServerUpdates|System.NullReferenceException: Object reference not set to an instance of an object.
   at Ghosts.Client.Comms.Updates.GetServerUpdates() in Z:\Projects\ghosts\src\Ghosts.Client\Comms\Updates.cs:line 74
2021/06/09 11:37:01.937|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381
2021/06/09 11:37:01.980|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381
2021/06/09 11:37:06.719|Ghosts.Client.Comms.Updates.PostClientResults|Problem posting logs to server System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.168.68.90:5000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at System.Net.WebClient.UploadString(String address, String data)
   at Ghosts.Client.Comms.Updates.PostResults(String fileName, ResultMachine machine, String postUrl, Boolean isDeletable) in Z:\Projects\ghosts\src\Ghosts.Client\Comms\Updates.cs:line 284
   at Ghosts.Client.Comms.Updates.PostClientResults() in Z:\Projects\ghosts\src\Ghosts.Client\Comms\Updates.cs:line 214
2021/06/09 11:37:21.236|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381
2021/06/09 11:37:21.283|Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook|System.Runtime.InteropServices.COMException (0x800401FA): Creating an instance of the COM component with CLSID {741BEEFD-AEC0-4AFF-84AF-4F61D15F5526} from the IClassFactory failed due to the following error: 800401fa Wrong OS or OS version for application (Exception from HRESULT: 0x800401FA (CO_E_WRONGOSFORAPP)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Ghosts.Client.Handlers.Outlook.SendEmailViaOutlook(EmailConfiguration emailConfig) in Z:\Projects\ghosts\src\Ghosts.Client\Handlers\Outlook.cs:line 381
---------------------------END OF LOG------------------------------------------------

The ghosts agent opens the Outlook application, but does not send any mail messages. 
The Word, Excel, and PowerPoint 2016 application work fine.
All my windows clients use Office 2016 and appreciate any help.
I am using the 64 bit version of Office 2016.

**Comment by sei-dupdyke** [comment]
Hi! Are you using a 32 or 64-bit version of office? (see this issue https://github.com/cmu-sei/GHOSTS/issues/49 - it may be related)

**Comment by fhbermudez** [comment]
I am using the 64 Bit version of Office 2016.
If I use the 64 Bit version of Office 365, it works fine. However 99% of my Win10 Workstation are using Office 2016.

**Comment by sei-dupdyke** [comment]
Oh sorry, I see that you had included that info at the bottom of the original post, my bad.

The short answer is that Outlook in particular seems super-finicky about versioning, with regards to our ability to control it in the manner that we do. This is dependent upon CLSIDs that GHOSTS references in order to get a handle to certain classes within Outlook.

I have some time today to look at this further, I'll report back here as I find a way forward.

Relatedly, we had been looking at automating Thunderbird so as to make email sim more flexible, I'm hoping to find some time to get back to that as well.

**Comment by sei-dupdyke** [comment]
I know there are problems with 64-bit office, but what throws me is that 365 is working. So, I just checked a range I have access to, and it runs office 2013 with 32-bit. I cloned a box and upgraded it to 365 and it still works, although it appears to be 64 bit.

After a bit of searching, it turns out O365 defaults to 32-bit regardless of OS.

For 64-bit 2016, I need to build you a copy of GHOSTS that is 64-bit. I am not sure what is involved with that. Standby.

**Comment by sei-dupdyke** [comment]
[Here is a 64-bit build of the GHOSTS client](https://cmu.box.com/s/3vpo16sbm8dg52p4tn129h0l6rjj9iuz) and it seems to work fine with my local 2016 64-bit install (I tested a few different timelines I have locally from some past ranges).

Sorry for the confusion, I'm going to update the docs to show the two versions. As always, LMK if you find anything janky going on with this version and I will fix-up as quickly as I can.

Thanks for checking out this project!

**Comment by fhbermudez** [comment]
I dowloaded the 64 Bit version and all seems to be working fine.
I will continue testing and let you know if I run into any more issues.
You got a really fine tool in ghosts.

Thanks!
